server:
  port: 8201
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #Use lowercase service-id
      routes: #Configure route paths
        - id: mall-auth
          uri: lb://mall-auth
          predicates:
            - Path=/mall-auth/**
          filters:
            - StripPrefix=1
        - id: mall-admin
          uri: lb://mall-admin
          predicates:
            - Path=/mall-admin/**
          filters:
            - StripPrefix=1
        - id: mall-portal
          uri: lb://mall-portal
          predicates:
            - Path=/mall-portal/**
          filters:
            - StripPrefix=1
        - id: mall-search
          uri: lb://mall-search
          predicates:
            - Path=/mall-search/**
          filters:
            - StripPrefix=1
        - id: mall-demo
          uri: lb://mall-demo
          predicates:
            - Path=/mall-demo/**
          filters:
            - StripPrefix=1
  data:
    redis:
      database: 0
      port: 6379
      host: 66.154.127.211
      password:
secure:
  ignore:
    urls: #Configure whitelist paths
      - "/doc.html"
      - "/v3/api-docs/swagger-config"
      - "/*/v3/api-docs/default"
      - "/*/v3/api-docs"
      - "/*/swagger-ui/**"
      - "/webjars/**"
      - "/favicon.ico"
      - "/webjars/**"
      - "/actuator/**"
      - "/mall-auth/**"
      - "/mall-search/**"
      - "/mall-portal/sso/login"
      - "/mall-portal/sso/register"
      - "/mall-portal/sso/getAuthCode"
      - "/mall-portal/home/**"
      - "/mall-portal/product/**"
      - "/mall-portal/brand/**"
      - "/mall-portal/alipay/**"
      - "/mall-admin/admin/login"
      - "/mall-admin/admin/register"
      - "/mall-admin/minio/upload"
management:
  endpoints:
    web:
      exposure:
        include: '*' #Expose Actuator monitoring endpoints
  endpoint:
    health:
      show-details: always #Show health details
    env:
      show-values: always #By default Actuator's environment variables are displayed as ****, enable display here
    configprops:
      show-values: always #By default Actuator's configuration properties are displayed as ****, enable display here
    info:
      enabled: true
knife4j:
  gateway:
    enabled: true
    strategy: discover #Gateway document aggregation method: service discovery (automatic aggregation)
    discover:
      version: openapi3 #Configure OpenAPI3 specification
      enabled: true #Configure to enable service discovery
      excluded-services: mall-monitor #Exclude monitoring service
    tags-sorter: order #Configure tag sorting rule
    operations-sorter: order #Configure operation sorting rule
sa-token:
  # token name (also the cookie name)
  token-name: Authorization
  # token validity period, unit seconds, -1 means never expire
  timeout: 2592000
  # token temporary validity period (if no operation within the specified time, the token is considered expired), unit seconds
  active-timeout: -1
  # Whether to allow concurrent login for the same account (when false, new login kicks out old login)
  is-concurrent: true
  # When multiple people log in to the same account, whether to share one token (when false, create a new token for each login)
  is-share: false
  # token style
  token-style: uuid
  # Whether to output operation log
  is-log: false
  # Whether to read token from cookie
  is-read-cookie: false
  # Whether to read token from head
  is-read-header: true
  # token prefix
  token-prefix: Bearer
  # Whether to print banner
  is-print: false

